### PR TITLE
Eeprom in external SPI flash

### PR DESCRIPTION
**Pull request by sobieh**
This allows to use MKS Robin Nano external flash over SPI2 to read/write data like EEPROM.
There is 8MB of storage there and the area 0x700000 - 0x800000 is not used by the original stock firmware.

I could use the dedicated EEPROM chip but I2C on STM32F1 is a real PITA and requires lots of fixes to work (bugs at chip level) so there was no point in playing with it. Flash memory is far better :D

This PR should work on any Robin Nano board like Sapphire Pro out of the box just after flashing firmware.

### CODE REVIEW

**Comment by inib** [comment]
Thank you very much, I'll give it a try as soon as I can.
Had already tried some stuff, but failed to get it to work parallel to the touch interface.

**Comment by sobieh** [comment]
It's because the XPT library was trying to configure SPI2 pins exclusively for Touch use via SoftSPI ... (that code sucks). I changed it to begin() / end() which configures and deconfigures the pins and allowing the real hardware SPI2 to work (actually the opposite :D).

**Comment by berghauz** [comment]
There is no actual bug with i2c and stm32, there is a bug in mks bootloader (PB7 pin share FSMC_NADV and I2C1_SDA simultaneously). It initialize fsmc bus and leave it active before run firmware and more over - you need to disable fsmc every time you access i2c bus xD MKS Robin series is a real junk. This little piece of code in HAL init (and eeprom access) fixes this
`rcc_clk_disable(RCC_FSMC);`
but there is another approach - marlin haven't support AT24C16N eeprom, so you need to handle this too. I have made this changes for my robin mini board, check [AT24C16.zip](https://github.com/inib/Marlin/files/4051114/AT24C16.zip).

**Comment by GeraltR** [comment]
Thank you for your help. I copy one file in the HAL_STM32F1 folder and 
then in the shared folder. In persistent_store_eeprom.cpp I need to 
change the motherboard and name tft as I have it in config.h. 
I2cEeprom.cpp I need to change the name to eeprom_i2c.cpp because this 
is the main one. But it doesn't work :(

W dniu 2020-01-12 20:07, Alexey Polyakov napisał(a):

**Comment by berghauz** [comment]
This will not work with just copying files and there is more  - this files from bugfix marlin half an year old :D
If this feature so crucial, i can find some spare time and make a PR into this repo (i really dunno how much reasonable it is as this repo outdated from marlin head too)

**Comment by GeraltR** [comment]
I think maybe I will write a notification in git.

Edit: Sorry, that's my mistake. It works, I look at the result of two problems and I got the wrong solution.

W dniu 2020-01-12 23:04, Alexey Polyakov napisał(a):

**Pull request merged**
